# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt5_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from naver_add_buddy_ver2 import init_driver, LOGIN_THREAD
from qt5_blog import blog

import sys
from datetime import datetime

year = 2022
month = 7
day = 30


class Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(223, 117)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 30, 206, 81))
        self.widget.setObjectName("widget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_id = QtWidgets.QLabel(self.widget)
        self.label_id.setObjectName("label_id")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_id)
        self.edit_id = QtWidgets.QLineEdit(self.widget)
        self.edit_id.setText("")
        self.edit_id.setObjectName("edit_id")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_id)
        self.label_pw = QtWidgets.QLabel(self.widget)
        self.label_pw.setObjectName("label_pw")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pw)
        self.edit_pw = QtWidgets.QLineEdit(self.widget)
        self.edit_pw.setText("")
        self.edit_pw.setObjectName("edit_pw")
        self.edit_pw.setEchoMode(QtWidgets.QLineEdit.Password)

        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_pw)
        self.btn_login = QtWidgets.QPushButton(self.widget)
        self.btn_login.setObjectName("btn_login")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btn_login)
        self.btn_next = QtWidgets.QPushButton(self.widget)
        self.btn_next.setObjectName("btn_next")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_next)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.title.setObjectName("title")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # init
        self.current_driver = None
        self.login_page = Form

        # disable
        self.btn_next.setDisabled(True)
        # callbacks
        self.btn_login.clicked.connect(self.naver_login)
        self.btn_next.clicked.connect(self.crawling_page)
        self.next_page = QtWidgets.QWidget()
        self.driver_1 = None

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "%d-%d-%d" % (year, month, day)))
        self.label_id.setText(_translate("Form", "아이디"))
        self.edit_id.setPlaceholderText(_translate("Form", "네이버 아이디"))
        self.label_pw.setText(_translate("Form", "비밀번호"))
        self.edit_pw.setPlaceholderText(_translate("Form", "네이버 비밀번호"))
        self.btn_login.setText(_translate("Form", "로그인"))
        self.btn_next.setText(_translate("Form", "다음"))
        self.title.setText(_translate("Form", "네이버 이웃 추가 프로그램"))

    def naver_login(self):
        self.current_driver = init_driver()
        id_ = self.edit_id.text()
        pw = self.edit_pw.text()
        try:
            # self.naver_macro.login(ID=id_, PW=pw)
            login = LOGIN_THREAD(self.current_driver, id_, pw)
            self.driver_1 = login.driver
            login.setDaemon(True)
            login.start()
            self.btn_login.setDisabled(True)
            # able
            self.btn_next.setDisabled(False)
        except:
            print("[QT ERROR] login")
            sys.exit()

    def crawling_page(self):
        try:
            ui = blog()
            ui.setupUi(self.next_page, self.driver_1, ui)
            self.next_page.show()
            self.login_page.close()
        except:
            sys.exit()


def dialog_msg():
    mbox = QtWidgets.QMessageBox()
    mbox.setWindowTitle("Yoon Company")
    mbox.setText("이용 가능 기간이 지났습니다.")
    mbox.setStandardButtons(QtWidgets.QMessageBox.Ok)

    mbox.exec_()


if __name__ == "__main__":
    if datetime.now() <= datetime(year, month, day, 0, 0, 0):
        app = QtWidgets.QApplication(sys.argv)
        app.setStyle("Fusion")
        Form = QtWidgets.QWidget()
        ui = Login()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
    else:
        app = QtWidgets.QApplication(sys.argv)
        app.setStyle("Fusion")
        dialog_msg()
