# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt5_blog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import webbrowser
from qt5_buddy import buddy
from naver_add_buddy_ver2 import CRAWLING_THREAD
import sys


class blog(object):
    def setupUi(self, Form, macro, blog):
        self.blog = blog
        Form.setObjectName("Form", )
        Form.setFixedSize(311, 290)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(5, 4, 301, 281))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.title = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.title.setObjectName("title")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.title)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_keyword = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_keyword.setObjectName("label_keyword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_keyword)
        self.edit_keyword = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_keyword.setText("")
        self.edit_keyword.setObjectName("edit_keyword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_keyword)
        self.label_page = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_page.setObjectName("label_page")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_page)
        self.edit_page = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.edit_page.setObjectName("edit_page")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_page)
        self.btn_next2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_next2.setObjectName("btn_next2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_next2)
        self.btn_blog = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_blog.setObjectName("btn_blog")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btn_blog)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.list_buddy = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.list_buddy.setObjectName("list_buddy")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.list_buddy)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.next_page2 = QtWidgets.QWidget()
        self.crawling_blog_page = Form
        
        # callbacks
        self.driver_1 = macro
        self.crawling = None
        self.btn_blog.clicked.connect(self.get_parsing)
        self.list_buddy.itemDoubleClicked.connect(lambda:self.double_click_event(self.blog))
        self.btn_next2.clicked.connect(lambda:self.add_buddy_func(self.blog))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "블로그 크롤링"))
        self.title.setText(_translate("Form", "네이버 이웃 추가 프로그램 ver1.3"))
        self.label_keyword.setText(_translate("Form", "키워드"))
        self.edit_keyword.setPlaceholderText(_translate("Form", "맛집"))
        self.label_page.setText(_translate("Form", "페이지 "))
        #self.edit_page.setPlaceholderText(_translate("Form", "1"))
        self.edit_page.setRange(1,100)
        self.btn_next2.setText(_translate("Form", "다음"))
        self.btn_blog.setText(_translate("Form", "블로그"))
        self.btn_next2.setDisabled(True)
        
    def get_parsing(self):
        self.url_list = []
        self.list_buddy.clear()
        if not self.edit_page.value(): page = 1
        else: page = self.edit_page.value()
        
        if not self.edit_keyword.text(): keyword = "맛집"
        else: keyword = self.edit_keyword.text()
                
        try:
            self.crawling = CRAWLING_THREAD(self.driver_1, keyword, page, self.list_buddy)
            self.crawling.setDaemon(True)
            self.crawling.start()
            self.btn_blog.setDisabled(True)
            self.btn_next2.setDisabled(False)

        except:
            print("[ERROR] QT5 Parsing")
        
    def double_click_event(self, _):
        webbrowser.open(str(self.list_buddy.currentItem().text()))

    def add_buddy_func(self, _):
        try:
            ui = buddy()
            ui.setupUi(self.next_page2, self.crawling.driver, self.crawling.mobile_blog_url_list, ui)
            self.next_page2.show()
            self.crawling_blog_page.close()
        except:
            sys.exit()    

    
if __name__ == "__main__":
    print("Test")
