# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt5_buddy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from naver_add_buddy_ver2 import BUDDY_THREAD


class buddy(object):
    def setupUi(self, Form, driver, url,ui):
        self.buddy = ui
        self.driver_2 = driver
        self.url_list = url
        
        Form.setObjectName("Form")
        Form.setFixedSize(330, 340)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(4, 5, 321, 331))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_add_buddy_cnt = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_add_buddy_cnt.setObjectName("label_add_buddy_cnt")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_add_buddy_cnt)
        self.edit_add_buddy_cnt = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        #self.edit_add_buddy_cnt.setText("")
        self.edit_add_buddy_cnt.setObjectName("edit_add_buddy_cnt")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_add_buddy_cnt)
        self.label_cnt = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_cnt.setObjectName("label_cnt")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_cnt)
        self.edit_group = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.edit_group.setObjectName("edit_group")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_group)
        self.edit_content = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.edit_content.setObjectName("edit_content")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.edit_content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add_buddy = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_add_buddy.setObjectName("btn_add_buddy")
        self.horizontalLayout.addWidget(self.btn_add_buddy)
        self.btn_stop = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.list_log = QtWidgets.QListWidget(self.formLayoutWidget_2)
        self.list_log.setObjectName("list_log")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.list_log)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.formLayout)
        self.title = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.title.setObjectName("title")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.title)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.btn_add_buddy.clicked.connect(lambda:self.add_buddy(self.buddy))
        self.btn_stop.clicked.connect(lambda:self.stop_event(self.buddy))
        self.buddy_obj = None
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "서로 이웃 추가"))
        self.label_add_buddy_cnt.setText(_translate("Form", "신청 이웃 수"))
        #self.edit_add_buddy_cnt.setPlaceholderText(_translate("Form", "최대 100명 신청 가능"))
        self.label_cnt.setText(_translate("Form", "그룹 번호"))
        #self.edit_group.setPlaceholderText(_translate("Form", "1"))
        self.edit_content.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">우리 서로 이웃해요~!</p></body></html>"))
        self.btn_add_buddy.setText(_translate("Form", "서로 이웃 신청"))
        self.btn_stop.setText(_translate("Form", "중단"))
        self.label.setText(_translate("Form", "로그"))
        self.title.setText(_translate("Form", "네이버 서로 이웃 추가 프로그램 ver1.3"))
        self.edit_add_buddy_cnt.setRange(1,200)
        self.edit_group.setRange(1,10)
        
        
    def add_buddy(self,_):
        if not self.edit_group.value(): group_idx = 0
        else: group_idx = int(self.edit_group.value()) -1
        if not self.edit_add_buddy_cnt.value(): wanted_buddy = 1
        else: wanted_buddy = int(self.edit_add_buddy_cnt.value())
        if wanted_buddy > 100:
            wanted_buddy = 100
        
        if not self.edit_content.toPlainText(): content = "우리 서로이웃해요."
        else: content = self.edit_content.toPlainText()
        
        self.buddy_obj = BUDDY_THREAD(self.driver_2, self.url_list, content, group_idx, wanted_buddy, self.list_log, True)
        self.buddy_obj.setDaemon(True)
        self.buddy_obj.start()    

    def stop_event(self,_):
        if self.buddy_obj.status == True:
            self.buddy_obj.status = False
        self.btn_stop.setDisabled(True)
if __name__ == "__main__":
    print("Test")
